# Generated by Django 2.0 on 2018-10-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num', models.IntegerField()),
                ('team1', models.CharField(max_length=200)),
                ('team2', models.CharField(max_length=200)),
                ('winner', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rank', models.IntegerField(default=999)),
                ('player1', models.TextField(help_text='Enter Player 1 name', max_length=100)),
                ('player2', models.TextField(help_text='Enter Player 2 name', max_length=100)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
