# Generated by Django 2.0 on 2018-10-05 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='serial_num',
        ),
        migrations.RemoveField(
            model_name='team',
            name='rank',
        ),
        migrations.AddField(
            model_name='match',
            name='team3',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
