# Generated by Django 2.0 on 2018-10-05 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20181005_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team4',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
