# Generated by Django 2.0 on 2018-10-05 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_match_team4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team3',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='title',
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Default_team1', to='catalog.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Default_team2', to='catalog.Team'),
        ),
    ]
